// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYOpU3ykxHbxmSA6i5OWZKJDZmn3efvDc',
    appId: '1:176924342445:web:2419ea6b5d25320a1f2e24',
    messagingSenderId: '176924342445',
    projectId: 'shopping-cart-f33f9',
    authDomain: 'shopping-cart-f33f9.firebaseapp.com',
    storageBucket: 'shopping-cart-f33f9.firebasestorage.app',
    measurementId: 'G-KV8CNZBRP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLhOXw_6LlANFtDxwVoLfp32RGqcQCy5k',
    appId: '1:176924342445:android:a24a55369c0183151f2e24',
    messagingSenderId: '176924342445',
    projectId: 'shopping-cart-f33f9',
    storageBucket: 'shopping-cart-f33f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogsA7VWwnOTsg8uEMGTpzozDJxGpd7Hc',
    appId: '1:176924342445:ios:081e854d59dd28ed1f2e24',
    messagingSenderId: '176924342445',
    projectId: 'shopping-cart-f33f9',
    storageBucket: 'shopping-cart-f33f9.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAogsA7VWwnOTsg8uEMGTpzozDJxGpd7Hc',
    appId: '1:176924342445:ios:081e854d59dd28ed1f2e24',
    messagingSenderId: '176924342445',
    projectId: 'shopping-cart-f33f9',
    storageBucket: 'shopping-cart-f33f9.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYOpU3ykxHbxmSA6i5OWZKJDZmn3efvDc',
    appId: '1:176924342445:web:b906f633322ae0831f2e24',
    messagingSenderId: '176924342445',
    projectId: 'shopping-cart-f33f9',
    authDomain: 'shopping-cart-f33f9.firebaseapp.com',
    storageBucket: 'shopping-cart-f33f9.firebasestorage.app',
    measurementId: 'G-9TMT13FJJL',
  );
}
